import { Montserrat, Work_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={` ${workSans.variable} ${montserrat.variable} antialiased`}
        >
          <Header></Header>
          <main className="px-8 sm:px-12 md:px-20 lg:px-30">{children}</main>
          <Footer></Footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
