// Katinka - Layout

import { Montserrat, Work_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollBar from "@/components/ScrollBar";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Modernia Curators",
  // description: "Generated by create next app",
  icons: {
    icon: "../favicon-32x32.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={` ${workSans.variable} ${montserrat.variable} antialiased`}
        >
          <ScrollBar />
          <Header />
          <main className="scroll-smooth px-8 sm:px-12 md:px-20 lg:px-30">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
